# Generated by Django 3.2.23 on 2023-11-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(default='Type your Message', max_length=1000, null=True),
        ),
    ]
