# Generated by Django 3.2.23 on 2023-11-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_rename_image_gallery_school_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='school_gallery',
            field=models.ImageField(default='upload/gallery/profile.jpg', upload_to='upload/gallery'),
        ),
    ]
