# Generated by Django 3.2.23 on 2023-11-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staff',
            new_name='staffs',
        ),
    ]
