# Generated by Django 3.2.23 on 2023-11-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_rename_staff_staffs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='school_gallery',
            new_name='photo',
        ),
    ]
