# Generated by Django 3.2.23 on 2023-11-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
