# Generated by Django 3.2.23 on 2023-11-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_delete_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
