# Generated by Django 3.2.23 on 2023-11-29 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='messagess',
        ),
    ]
