# Generated by Django 3.2.23 on 2023-12-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_rename_messages_messagess'),
    ]

    operations = [
        migrations.CreateModel(
            name='enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('pno', models.IntegerField()),
                ('nid', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('yoe', models.IntegerField()),
                ('coursecate', models.CharField(max_length=150)),
                ('tcourse', models.CharField(max_length=100)),
                ('upbirth', models.FileField(upload_to='')),
            ],
        ),
    ]
