# Generated by Django 3.2.23 on 2023-12-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='upbirth',
            field=models.FileField(upload_to='upload/enrolls'),
        ),
    ]
