# Generated by Django 3.2.23 on 2023-12-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_enroll_upbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='upid',
            field=models.FileField(default='upload/enroll/id.pdf', upload_to='upload/enrolls'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='upkcse',
            field=models.FileField(default='upload/enroll/kcse.pdf', upload_to='upload/enrolls'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='upbirth',
            field=models.FileField(default='upload/enroll/birth.pdf', upload_to='upload/enrolls'),
        ),
    ]
