# Generated by Django 3.2.23 on 2023-12-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20231207_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='name',
            new_name='namee',
        ),
    ]
