# Generated by Django 3.2.23 on 2023-12-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_rename_name_enroll_namee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='namee',
            new_name='name',
        ),
    ]
