# Generated by Django 3.2.23 on 2023-12-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_rename_name_enroll_fname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='fname',
            new_name='firstname',
        ),
    ]
