# Generated by Django 3.2.23 on 2023-12-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_rename_firstname_enroll_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='coursecate',
            new_name='course_cate',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='tcourse',
            new_name='t_course',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='upbirth',
            new_name='up_birth',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='upid',
            new_name='up_id',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='upkcse',
            new_name='up_kcse',
        ),
    ]
