# Generated by Django 3.2.24 on 2024-07-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20231211_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='first_name',
            new_name='firstname',
        ),
    ]
