# Generated by Django 3.2.24 on 2024-07-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
