# Generated by Django 3.2.24 on 2024-07-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_alter_testimonial_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='upload/our team/team.png', upload_to='upload/our team')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
