# Generated by Django 3.2.24 on 2024-07-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_ourteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='position',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
